### ISSUE TITLE
Handle error when LND server is not available

### ISSUE THREAD

**Issue by PeterRounce** [boltcard/boltcard#23]
`There is a Panic in the code when trying to pay the invoice and gRPC address:port is incorrect/unreachable..noticed it in the server logs when forgot to update settings in the config file after IP address change for domain..no harm done as service bounced back up automatically.` @honeybol on [Bolt Card group](https://t.me/bolt_card)

This should be caught and handled gracefully without the service restart.

**Comment by 3jtechtest** [comment]
Dec 25 18:05:15 : {"level":"info","msg":"unable to connect to x.x.x.x:10009: %!w(context.deadlineExceededError={})","time":"2022-12-25T18:05:15Z"}
Dec 25 18:05:15 bash[1160682]: panic: context deadline exceeded
Dec 25 18:05:15 bash[1160682]: goroutine 66 [running]:
Dec 25 18:05:15  bash[1160682]: main.getGrpcConn()
Dec 25 18:05:15 t bash[1160682]:         /home/ubuntu/boltcard/lightning.go:68 +0x639
Dec 25 18:05:15  bash[1160682]: main.pay_invoice()
Dec 25 18:05:15 bash[1160682]:         /home/ubuntu/boltcard/lightning.go:205 +0x265
Dec 25 18:05:15 bash[1160682]: created by main.lnurlw_callback
Dec 25 18:05:15  bash[1160682]:         /home/ubuntu/boltcard/lnurlw_callback.go:157 +0x131d
Dec 25 18:05:15 systemd[1]: boltcard.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
